### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [elastic/app-search-javascript#34]
I would like to create a file contributing.md and add following -
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

**Comment by JasonStoltz** [comment]
I don't mind having a contributing.md guide, but I think this is too low level, there are plenty of generic guides online that describe the process stated above already.
