### ISSUE TITLE
Support filters in query suggestion

### ISSUE THREAD

**Issue by panpanpandas** [elastic/app-search-javascript#36]
We have a use case where we would like to add filters in query suggestion (e.g. filter out disabled products). Elastic Search itself supports the use case, however, app search doesn't support filters yet. Could you add the support? Thanks in advance!

App search query suggestion doc - https://www.elastic.co/guide/en/app-search/current/query-suggestions-guide.html
Elastic Search suggester doc - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html

**Comment by JasonStoltz** [comment]
I will pass this feedback onto the product team, thanks!

**Comment by 684efs3** [comment]
Has this been added? I would like to add a geospatial filter, like mentioned here: 
https://swiftype.com/documentation/site-search/searching/filtering

![Screen Shot 2022-04-21 at 11 35 51 AM](https://user-images.githubusercontent.com/48864759/164497599-33bee256-6434-4fc7-a549-d2096fbd6d7d.jpg)
