### ISSUE TITLE
Geo-Bounding Box Query in App Search

### ISSUE THREAD

**Issue by ethanhoroschak** [elastic/app-search-javascript#43]
**Is your feature request related to a problem? Please describe.**
We need to Geo-Bounding Box Query to filter results in a certain area and would like to use App Search to optimize our search experience.

**Describe the solution you'd like**
Addition of Geo-Bounding Box Query functionality to App Search api.

**Describe alternatives you've considered**
We've built our search using ElasticSearch api and have implemented Geo-Bounding Box Query, however, we'd like to use App Search for the search tuning features and ease of use .

**Comment by JasonStoltz** [comment]
Awesome suggestion. Since this is specific to Elastic App Search, I'm going to pass it on to them and close the issue here.

FWIW, without going into specifics, I do think there is a feature in the works that could solve your issue here.
