### ISSUE TITLE
v8.6+ unable to import and build with Vite

### ISSUE THREAD

**Issue by jayjfletcher** [elastic/app-search-javascript#49]
When upgrading from v8.5.1 to v8.6 or v8.7 my builds start failing with Vite.

I get the following error:

> Failed to resolve entry for package "@elastic/app-search-javascript". The package may have incorrect main/module/exports specified in its package.json

Any ideas?

Again I've narrowed it down to upgrading it past v8.5.1.

**Comment by arvenom** [comment]
same issue here :(

**Comment by jayjfletcher** [comment]
Is development active on this repo?

**Comment by joemcelroy** [comment]
Hi @jayjfletcher,

Will look into this!

**Comment by joemcelroy** [comment]
The issue is vite (and other build systems that rely on ES modules) relied on the es export that didn't exist. 

I've deprecated 8.7.0 and 8.6.0 and published a new version for 8.7.1. This is now available from NPM https://www.npmjs.com/package/@elastic/app-search-javascript

**Comment by joemcelroy** [comment]
built a codesandbox template https://codesandbox.io/s/nifty-neco-omxd5l?file=/src/App.tsx to verify this is working well with vite 🎉

**Comment by jayjfletcher** [comment]
Awesome, thanks for getting back to me and getting that pushed out.
